# -*- coding: utf-8 -*-
"""analise_telecom

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gc6qo8Xw5orgYmmBfM00lF792W4zQ0-y

# Análise de Dados com Python

### Desafio:

Você trabalha em uma empresa de telecom e tem clientes de vários serviços diferentes, entre os principais: internet e telefone.

O problema é que, analisando o histórico dos clientes dos últimos anos, você percebeu que a empresa está com taxa de cancelamento de mais de 26% dos clientes.

Isso representa uma perda de milhões para a empresa.

O que a empresa precisa fazer para resolver isso?

Base de dados: https://www.kaggle.com/radmirzosimov/telecom-users-dataset

# Passo a passo
***



1.   Importar a base de dados
2.   Visualizar a base de dados para entender o que temos disponível
3.   Realizar o tratamento dos dados (importante)
4.   Verificar como está a distribuição de cancelamentos
5.   Fazer uma análise das causas dos cancelamentos
6. Conclusões

# Importar a base de dados
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import plotly.express as px
import seaborn as sns
# %matplotlib inline

"""# Visualizar o que há disponível na base"""

tabela_clientes = pd.read_csv('/content/drive/MyDrive/bases_de_dados/telecom_users.csv')
tabela_clientes.head()

# removendo colunas que não serão utilizadas
tabela_clientes = tabela_clientes.drop(columns=['Unnamed: 0'])

"""# Tratamento dos dados"""

tabela_clientes.info()

# transformando o tipo de TotalGasto em numeric
tabela_clientes['TotalGasto'] = pd.to_numeric(tabela_clientes['TotalGasto'], errors='coerce')
tabela_clientes.info()

# removendo a coluna Código que possui todos os valores vazios
tabela_clientes = tabela_clientes.dropna(how='all', axis=1)
tabela_clientes.dropna(inplace=True)
tabela_clientes.info()

"""# Distribuição de cancelamentos"""

tabela_clientes['Churn'].value_counts(normalize = True).apply('{:.2%}'.format)

"""# Análise de causas dos cancelamentos"""

teste = px.histogram(tabela_clientes, x='ServicoInternet', color='Churn', width=500, height=400,
                       labels={
                           'ServicoInternet': 'Serviço de Internet',
                           'Churn': 'Cancelou'
                       },
                       title={
                           'text': 'Cancelamentos por serviço de Internet',
                           'y':0.9,
                            'x':0.5,
                           'xanchor': 'center',
                            
                       },)

teste.show()

# utilizando um for para criar todas os gráficos dinâmicamente
for coluna in tabela_clientes:
    if coluna == 'IDCliente':
        continue
    grafico = px.histogram(tabela_clientes, x=coluna, color='Churn', width=500,
                           height=400, labels={
                               'Churn': 'Cancelou? '
                           })
    grafico.show()

"""# Conclusões e Ações

Conclusões desta análise:





*   A empresa tem dificuldade em reter os clientes. As taxas de cancelamento nos 10 primeiros meses são grandes.
*   Há um problema nos serviços de Fibra, os clientes de Fibra cancelam muito
mais que os clientes de outros serviços.
*   Clientes que possuem vários serviços tem MUITO menos chance de cancelar
*   Clientes com contrato mensal cancelam MUITO mais que os outros modos
*   Clientes que utilizam boleto como forma de pagamento tendem a cancelar mais
"""